apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "slackernews"
  labels:
    app.kubernetes.io/name: "slackernews"
    app.kubernetes.io/version: "0.0.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "slackernews"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  descriptor:
    version: "1.0.0"
    description: "SlackerNews"
    icons:
      - src: "https://uploads-ssl.webflow.com/6310ad0e6a18aa1620da6ae8/6330e04f42bc6a7ba03b4725_snicon.png"
        type: "image/png"
    type: slackernews
    links:
      - description: ðŸ”— Open Slackernews
        url: "http://slackernews"
#      - description: Slackernews Admin
